### ISSUE TITLE
It  not work  in tns Angular 2 project, only work in js project. -Resolved.

### ISSUE THREAD

**Issue by Arthurisme** [NathanaelA/nativescript-orientation#1]
show as:
Fail to find module:"nativescript-orientation", relative to :/app/tns_modules/

**Comment by NathanaelA** [comment]
I haven't had any other complaints about this in a ng2 project.  How are you loading it?

**Comment by Arthurisme** [comment]
Hi, Nathanael,
I just put this line in my ts file:
require( "nativescript-orientation" );

**Comment by Arthurisme** [comment]
it is wok now, because i use livesync, when I use run android to build the app. It is work.

Sorry to cost your time.

**Comment by magar91** [comment]
I'm having this issue what is the correct way to import it?, I am using

```javascript
import orientation = require('nativescript-orientation');
```

**Comment by NathanaelA** [comment]
try:
`const orientation = require('nativescript-orientation');`

**Comment by magar91** [comment]
still no luck @NathanaelA this is my console output: 

`file:///app/app.component.ts:17:28: JS ERROR Error: Could not find module 'nativescript-orientation'`

**Comment by NathanaelA** [comment]
@magar91 -- Have you done a `tns build ios` or `tns build android` (do not add a --watch) after you did the `tns plugin add nativescript-orientation`?

If not this is the reason, live sync'ing will not transfer the new plugin to the phone/emulator without a rebuild of the app.

**Comment by magar91** [comment]
It worked now, I was using the command `tns run` but didn't worked that way, also I tried it out in a project created with telerik platform appBuilder but it didn't worked for me, just pointing it out. Thanks for your help

**Comment by kurodakenjiro** [comment]
In tns angluar 2 project
I cannot use this function : exports.orientation(args)
and I'll try to use this type( .landscape stackLayout { background-color:black; }  ) in login-common.css,
but It doesn't work.

**Comment by NathanaelA** [comment]
@kurodakenjiro - I haven't run any tests with ng2; I develop almost exclusively with PAN (Plain Awesome NativeScript) so my plugins work for sure w/ PAN; some lower level plugins (like this one) might not work w/ NG2...
