### ISSUE TITLE
Right Landscape Doesnt Work as Expected

### ISSUE THREAD

**Issue by talatccan** [NathanaelA/nativescript-orientation#12]
Hi,

I have a problem with right landscape. I didnt use any parameter like right or left. I only imported it and put landscape in css. However its working for left landscape but its not working for right landscape. 

PS: When i tried turn it from left to right, right landscape worked without problem.

So it doesnt work if i first turn it right.

**Comment by NathanaelA** [comment]
@talatccan - There is a pull request that might fix this; I haven't had a chance to look at it yet..

**Comment by NathanaelA** [comment]
I believe this should now be fixed in the latest version!
