### ISSUE TITLE
Issues with the CSS plugin?

### ISSUE THREAD

**Issue by d3mac123** [NathanaelA/nativescript-orientation#15]
I am using both plugins (orientation and CSS) and I am trying to have something like this (not working):
.android .compass {
    width: 100;
    height: 100;
    margin-left: -250;
    margin-bottom: -350;
}
/* Tried both examples below */
.android .landscape .compass {
    width: 100;
    height: 100;
    margin-left: -0;
    margin-bottom: -350;
}
.landscape .android .compass {
    width: 100;
    height: 100;
    margin-left: -0;
    margin-bottom: -350;
}

How to do that?

**Comment by NathanaelA** [comment]
There is a small trick to this.   It needs to be: `.android.landscape` no space between them, there are both assigned on the same class group; so NativeScript only will accept it with them together.

```
.android.landscape .compass {
width: 100;
height: 100;
margin-left: -0;
margin-bottom: -350;
}
```

**Comment by d3mac123** [comment]
Got it. Thanks. However, the CSS applies correctly only when I rotate to one side:
![screen shot 2017-05-15 at 3 38 37 pm](https://cloud.githubusercontent.com/assets/229148/26075826/b5783d52-3984-11e7-9181-83290c3867eb.png)

When I rotate to the "other side", see what happens with the Compass (in the left/bottom corner):
![screen shot 2017-05-15 at 3 38 50 pm](https://cloud.githubusercontent.com/assets/229148/26075833/bfb96a84-3984-11e7-807d-8981feeec09c.png)

Any ideas how to fix that?

**Comment by NathanaelA** [comment]
Yes, I have a pull request I haven't tested yet that should fix it...

**Comment by NathanaelA** [comment]
Can you try the latest, I believe it is now fixed.
