### ISSUE TITLE
Disabling rotation on one view disables it for all application views

### ISSUE THREAD

**Issue by ryanzaatari** [NathanaelA/nativescript-orientation#16]
I'm currently using orientation.disableRotation(); for my home view, but I noticed that all other views are now locked as well. is this how it's supposed to function ? is there a way to lock the rotation for only one view ?

**Comment by NathanaelA** [comment]
Yes, this is its design to disable rotation until you re-enable it.  
On your navigation to a new view; just re-enable rotation...
