### ISSUE TITLE
NativeScript 3.0: Causes error on iOS when used with nativescript-dom (t is undefined)

### ISSUE THREAD

**Issue by AdamDenoon** [NathanaelA/nativescript-orientation#19]
My app needs nativescript-dom upon initialization, but only needs nativescript-orientation in a single controller. When I require nativescript-orientation (in my controller) after having required nativescript-dom (earlier in app.js), I get the following error:

`JS ERROR TypeError: undefined is not an object (evaluating 't.cssClasses.forEach')`

(t is undefined)

This only occurs on iOS.

- CLI: `3.0.3`
- Cross-platform modules: `3.0.1`
- iOS Runtime: `3.0.1`
- Plugin(s): `nativescript-orientation: 1.6.1`, `nativescript-dom: 2.0.0`, `tns-core-modules: 3.0.1`

As a temporary workaround, and since I already have nativescript-dom required in my app.js, I've commented out line 26 of orientation.js:

`//require('nativescript-dom');`

**Comment by NathanaelA** [comment]
This has been fixed for a while.  Use the latest versions.
