### ISSUE TITLE
cannot get property of undefined

### ISSUE THREAD

**Issue by xerotolerant** [NathanaelA/nativescript-orientation#2]
I tried the nativescript-orientation plugin and setOrientation. 

    var orientation = require('nativescript-orientation');
    console.log(JSON.stringify(orientation));// outputs JS: {}
    orientation.setOrientation("portrait"); 

However I get the error "Cannot read property setOrientation of undefined".

tns plugin list lists the plugin so I am not sure what I might be doing wrong.

**Comment by MidiPWNZ** [comment]
This is with certainty related to the proccess of intalling TNS plugins, as it hase some Gotchas.

[AHHH! This NativeScript plugin doesn’t work](https://bradmartin.net/2016/07/20/ahhh-this-nativescript-plugin-doesnt-work/)

With the information given in the article, i could solve the Problem.

**Comment by NathanaelA** [comment]
@xerotolerant - After you do a `tns plugin add nativescript-orientation` you need to do a `tns run ios` or `tns run android`  (no other parameters).  And it should work fine.
