### ISSUE TITLE
page._refreshCss is not a function - NativeScript 3.3.0

### ISSUE THREAD

**Issue by elvismercado** [NathanaelA/nativescript-orientation#21]
After updating to nativescript 3.3.0 and version 2.0.0 of this package app crashes on launch.

Screenshot of error:
<img width="664" alt="screen shot 2017-10-31 at 09 57 47" src="https://user-images.githubusercontent.com/3658208/32217586-bcb43cdc-be28-11e7-88b5-a29aec456927.png">

As a temporary fix I removed line 301 in `orientation.js` and the problem no longer occurs.

Neither `page._refreshCss()` or `page._resetCssValues()` seem to exists

**Comment by alexandruantonica** [comment]
I have the same issue.

**Comment by NathanaelA** [comment]
Yeah, TNS 3.3 removed this function.   I have v2.01 that I will be releasing in the next hour or so that fixes this issue.    ;-)

**Comment by NathanaelA** [comment]
This is now fixed in 2.01 which I just released.   Plus the docs now show how to use the cool `.landscape` on all the screens in Angular.

**Comment by elvismercado** [comment]
great. thnx for being so fast
