### ISSUE TITLE
`setOrientation()` causes `ExpressionChangedAfterItHasBeenCheckedError`

### ISSUE THREAD

**Issue by rynop** [NathanaelA/nativescript-orientation#35]
Strange one here. iOS. `"nativescript-angular": "~7.1.0"`, `"nativescript-orientation": "~2.2.1"`

`landscape.component.ts`:

```javascript
...
  constructor(
    private route: ActivatedRoute,
    private page: Page,
    private routerExtensions: RouterExtensions
  ) {
    this.page.actionBarHidden = true;
  }

  ngOnInit() {
    this.id = this.route.snapshot.params['id'];
    orientation.setOrientation('landscape', false);
 }
```

my `landscape.component.html` is completely empty.

the `LandscapeComponent` is loaded via navigation from another component.  The `onCreate()` method is called from a `(tap)="onCreate()` button press:

```javascript
  async onCreate() {
    try {
      const item = await this.createItem();
      console.log(`Created`, item);

      this.routerExtensions.navigate(['../landscape', item.id], {
        clearHistory: true
      });
    } catch (error) {
      console.error('Problem creating', error);
    }
  }
```

If I comment out `orientation.setOrientation()` I don't get the error.

Any ideas?  FWIW it still flops the screen orientation to landscape.

**Comment by rynop** [comment]
The workaround I found is to add it into `ngAfterViewInit()` like so:

```javascript
  ngAfterViewInit() {
    orientation.setOrientation('landscape', false);
    orientation.disableRotation();
  }
```

Putting it in `ngOnInit()` will cause Zone view update problems, I think due to the Error preventing further processing.  It still throws the error, so if you have other logic in `ngAfterViewInit()` this hack may not work for you.
`

**Comment by NathanaelA** [comment]
In Angular  because it has change detection; this probably needs to be called either in the constructor, hopefully before change detection is calculated or wrapped in a zonedCallback so that the change detection is reset.
