### ISSUE TITLE
Xcodebuild failed with exit code 65: Plugin conflict nativescript-orientation and kinvey-nativescript-sdk

### ISSUE THREAD

**Issue by Beckmi2** [NathanaelA/nativescript-orientation#37]
I work with:
Sidekick 1.16.1 (I just updated to 1.16.2
Nodejs 10.14.1
ppm 6.4.1
Nativescript Cli 5.1.1
kinvey-nativescript-sdk 3.12.4
nativescript-orientation 2.2.1
-----------------------------
Update Sidekick 1.16.2 and Nativescript Cli 5.2.3 didn't solve the problem
-----------------------------------------------------

There is a plugin conflict between kinvey-nativescript-sdk and nativescript-orientation.

To make this issue rebuildable I created a new app with Sidekick, based on the template "Drawer Navigation", project type Javascript.

I installed the plugin kinvey-nativescript-sdk. Build IOS and Android ok.
The I installed the plugin nativescript-orientation. Android build ok. 
IOS build failed (**command xcodebuild failed with exit code 65**).

I deinstalled both plugins and tried the other way round. Same issue. One plugin is ok. But the second causes a failed build on IOS, no matter, which plugin comes first.

I also tried to install the plugins not via Sidekick, but via Terminal tns commands. Same issue.

Any idea?  Thanks for your help!
----------------------------------------------------------------
Here is the package-lock.json file and an text file with the Terminal Output:
[ios_build_failed.zip](https://github.com/NathanaelA/nativescript-orientation/files/2966683/ios_build_failed.zip)

**Comment by NathanaelA** [comment]
Actually I believe the issue is purely an Kinvey/sidekick issue; looking at the output log it is reporting several issues with Kinvey.   NS-Orientation has no native components; which means it is never seen by Xcode; only webpack.    I suspect that no matter what additional JS plugin you add; you will get this issue.    Based on https://github.com/NativeScript/sidekick-feedback/issues/329 I suspect that if you remove kinvey rebuild; then re-add kinvey it probably will fix it.

**Comment by Beckmi2** [comment]
@NathanaelA 
What do you mean with "remove kinvey  @rebuild"?
Do you mean, remove the folders hooks, node_modules and platforms. That is, what I always do after (de-)installing plugins. But it doesn't help.

**Comment by Beckmi2** [comment]
@NathanaelA 
Unfortunately removing nativescript-ui-sidedrawer and nativescript-ui-listivew (obviously the solution in   [NativeScript/sidekick-feedback#329](url)) didn't help in my case!
