### ISSUE TITLE
plugins orientation and listview 6.0.0 conflict

### ISSUE THREAD

**Issue by Beckmi2** [NathanaelA/nativescript-orientation#38]
[TestListView.zip](https://github.com/NathanaelA/nativescript-orientation/files/3000110/TestListView.zip)

See also:
[https://github.com/telerik/nativescript-ui-feedback/issues/1061](url)

_I have a project, which works fine with nativescript-ui-listview 5.1.1. But when I update to 6.0.0.  the menu item 'open' runs into an error._

_I have attached a zip-File, which contains the project._

_In the meantime I found out, which code causes the error: 
In **app.js** the statement
**require("nativescript-orientation");**_

_When I delete this statement, there is no error, when calling menu item 'open'._

### Which platform(s) does your issue occur on?
_Android 5.2.3_

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** 6.0.0.
- **CLI:** 5.2.3.
- **Cross-platform modules:** 5.2.2
- **Runtime(s):** tns-android: 5.0.0
### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application ..
2. Chose Item 'open' from menu.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
_I attached a runnable project (TestListView.zip)_

**Comment by NathanaelA** [comment]
Thanks for the project -- I can duplicate the issue.     The issue actually is a bug in the RadListView.    I have added a bug https://github.com/telerik/nativescript-ui-feedback/issues/1092

I can try/catch the call in my code to work around the issue for the next version; but the underlying bug should be fixed by the NS team.

**Comment by NathanaelA** [comment]
@Beckmi2 - This has already been fixed in the 6.2.0 of the RadListView.   ;-)
