### ISSUE TITLE
disableRotation() does not have any effect

### ISSUE THREAD

**Issue by SephReed** [NathanaelA/nativescript-orientation#40]
Calling `disableRotation()` appears to have no effect.

I get no errors, but rotating my device still rotates the app.

**Comment by NathanaelA** [comment]
@SephReed - Does this happen with the demo app?

**Comment by SephReed** [comment]
Sorry.  On iOS.  I'll test out the demo...

**Comment by SephReed** [comment]
It'll be a while before I test out this demo.  It's a bit involved.

But here's my code:

```
setOrientation("landscape");
disableRotation();
```

It sets the rotation to landscape, but if I rotate the phone a few times, it returns to portrait

**Comment by SephReed** [comment]
1. <img width="436" alt="Screen Shot 2019-05-13 at 5 47 41 PM" src="https://user-images.githubusercontent.com/14002040/57659252-4d658d80-75a7-11e9-813b-f4725499ec8c.png">
2. <img width="889" alt="Screen Shot 2019-05-13 at 5 47 51 PM" src="https://user-images.githubusercontent.com/14002040/57659253-4d658d80-75a7-11e9-8e32-9fd6ae94645f.png">
3. <img width="447" alt="Screen Shot 2019-05-13 at 5 47 57 PM" src="https://user-images.githubusercontent.com/14002040/57659254-4d658d80-75a7-11e9-80da-06c498d087d6.png">

**Comment by SephReed** [comment]
Wooooooh.  That was a doozy.

Found the offending line of code:

`app.run({ moduleName: "app-root" });`

Apparently, if you don't use `app.start()` the screen locking doesn't work.

Might want to add this to the docs, it makes for a pretty difficult bug to find.

**Comment by SephReed** [comment]
Doubly so because using app.start() gives the following console error:

>  application.start() is deprecated; use application.run()

**Comment by SephReed** [comment]
Actually, I'm going to close this issue and open a more specific one..
