### ISSUE TITLE
Using application.run() breaks screen locking

### ISSUE THREAD

**Issue by SephReed** [NathanaelA/nativescript-orientation#41]
Found this bug as a result of this prior issue: https://github.com/NathanaelA/nativescript-orientation/issues/40

For some reason, using `application.run()` instead of `application.start()` makes the screen locking aspect of this plugin no longer work.

Also, if you use `application.start()` you will get a deprecation warning in the console, urging to use `application.run()` instead.

**Comment by NathanaelA** [comment]
Yeah, that is really weird -- Thank you for figuring out how to duplicate it; I'll look at the code and see if I can figure out why one would work and the other won't on iOS.

**Comment by SephReed** [comment]
Thanks so much @NathanaelA 

Great plugin btw!

**Comment by NathanaelA** [comment]
@SephReed - Are you seeing this on a emulator (if so which one); or just on a real device.   I just tested it on a emulator, and it worked properly.   My real devices haven't been charged; so it will be a while before I can test on them...     I also just committed the latest demo, it has been updated to the current latest NativeScript).

**Comment by SephReed** [comment]
I'm on an iOS iPhone6 emulator.  I haven't tested it elsewhere.  Very strange bug.

I'll try downloading the new demo in a while and see what happens.

**Comment by NathanaelA** [comment]
@SephReed - Were you able to duplicate this with the later demo?

**Comment by SephReed** [comment]
I have not.  So sorry.  I don't have my work environment set up for doing phone development right now, but I think it's safe to close this issue.  If someone else runs into it (or I do again) it can always be re-opened.

Thank you.
